### ISSUE TITLE
IntegrateObjects error

### ISSUE THREAD

**Issue by galvaniquee** [MarianoRuzJurado/OrthoIntegrate#1]
Hi,

I tried my best to follow the tutorial and corrected some bugs in there such as species.2 should be "mouse" rather than "mice" etc. However I came to this bug that I am not sure how to correct 

> SeuratObject.combined <- IntegrateObjects(OrthologueList = Orthologue.DF, SeuratObjectList.species.1 = resultList.human$SeuratObjects, SeuratObjectList.species.2 = resultList.mice$SeuratObjects,species.1 = "human",species.2="mouse")

Error in RenameGenesSeurat(ObjList = SubsetList$SeuratObject.species2.list,  : 
  no slot of name "counts" for this object of class "Assay5"

I checked the seurat objects and there are "counts" in the Assay. May I know what additional information would you need and how should I proceed? Thanks

**Comment by MarianoRuzJurado** [comment]
Hi galvaniquee,

thank you for raising my attention to a bug in the package and for the need to update the tutorial. 
It seems that i introduced a bug into the function "SubsetList" when adding compatibility with zebrafish.

Since there was still code refering to a now renamed slot, the seurat objects could not be subsetted correctly and then not passed to the following functions resulting in a missing counts slots and the error message you faced.

I corrected the bug in the SubsetList function and now it should work fine.

Please let me know if you encounter anything else.

Best,
Mariano
